### ISSUE TITLE
Unable to upload and analyze file

### ISSUE THREAD

**Issue by carl-3** [cisagov/Malcolm#246] opened 2023-03-27 19:33 UTC
# 🐛 Summary #

Unable to upload pcap file via https://localhost/upload

## To reproduce ##

1. Navigate to https://localhost/upload
2. Select "Add files..."
3. Select desired PCAP and select "Open"
4. Click "Start Upload" (or click "Start") 
5. Notice that the previously selected PCAP/PCAPNG file has now disappeared. 

## Expected behavior ##

I expected that I would be able to upload and then analyze a file using the GUI.

## Any helpful log output or screenshots ##

It looks like the problem stems from opensearch crashing. 
![Screen Shot 2023-03-27 at 11 53 16](https://user-images.githubusercontent.com/113935499/228047057-37032ace-f1fa-4644-9ad5-d3adeb1803af.png)

**Comment by mmguero** [comment] 2023-03-27 20:55
duplicate of idaholab/Malcolm#167

**Closed as not planned by mmguero** 2023-03-27 20:55 UTC
