### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by Kush2000528** [cisagov/Malcolm#306] opened 2024-04-25 08:17 UTC
![Screenshot 2024-04-25 134225](https://github.com/cisagov/Malcolm/assets/132539966/1f58ab4d-00f3-4f81-a44d-0bdcb033ed77)

![Screenshot 2024-04-25 134258](https://github.com/cisagov/Malcolm/assets/132539966/fc8c87f1-afa3-4828-a202-6872317e7e4f)

There is issue in the docker-compose.yml file if my running container health check is failed then my container is down so the restart policy is set "no" how can i  set my container into a running state?

**Comment by mmguero** [comment] 2024-05-01 15:41
duplicate of 307

**Closed as not planned by mmguero** 2024-05-01 15:41 UTC
