### ISSUE TITLE
Netbox disabled

### ISSUE THREAD

**Issue by devilman85** [cisagov/Malcolm#258] opened 2023-05-25 09:45 UTC
{ "error": { "code": 422, "message": "The local service netbox has been disabled." } }
```

![Screenshot 2023-05-25 114358](https://github.com/cisagov/Malcolm/assets/54392935/d63a6fd7-d04f-4f85-a0c7-922706a8271d)

How can I solve this?

**Comment by mmguero** [comment] 2023-05-25 13:19
Duplicate of idaholab/Malcolm#203. Please don't log issues on both repositories.

**Closed as completed by mmguero** 2023-05-25 13:19 UTC
Labels: invalid
