### ISSUE TITLE
how to activate SFTP/SSH

### ISSUE THREAD

**Issue by e101sg** [cisagov/Malcolm#239] opened 2023-02-20 03:10 UTC
Dear All,

Greetings. New to Malcolm. Hope this right place to post a question. (this is not bug report). As described in the document, the SFTP server is running on 8022. But how to connect and upload the pcap file automatically or how to to ssh to Malcolm it self. 

Running Malcolm on top of Ubuntu 22.04 and changed  few things the **sshd_config** file under Malcolm/file-upload as shown in 
screen shot but still can not do sfrp or ssh to localhost  or Ubuntu IP 172.16.2.6 from another laptop in the network. 
Any advise will highly useful. Afraid i am making any basic mistake.  

![Malcolm_SFTP](https://user-images.githubusercontent.com/1925934/219999533-556fd0c3-4739-4bdf-8b1e-12834b1ab1cf.png)

Thanks and Cheers!

**Comment by Njinx** [comment] 2023-02-21 19:47
Unless I'm mistaken, I don't think `~/Malcolm/file-upload/sshd_config` is the correct config to change. The default path sshd reads from is `/etc/ssh/sshd_config`. Being unable to SSH `localhost -> localhost` is really strange. Is sshd running (`sudo systemctl status sshd`)?

**Comment by mmguero** [comment] 2023-02-22 01:03
The biggest issue is going to be whether or not the port forwarding is happening to forward the connections on the host to the upload container running sshd for these uploads.

When running `./scripts/install.py --configure` you'll be asked `Expose SFTP server (for PCAP upload) to external hosts? (y/N)`, and if you answer 'y` it should set up that port forwarding for you. The corresponding value in the docker-compose.yml file is [here](https://github.com/cisagov/Malcolm/blob/360fbd60dc99348503121c11f80fd348b0ad74be/docker-compose.yml#L853-L854) in the `upload` section:

```
    ports:
      - "0.0.0.0:8022:22"
```

If the IP address there is set to `0.0.0.0` it means that hosts external to that computer will be able to connect to port 8022 and access that SFTP server. You may have to open ports on your firewall to do so (ie., something like `sudo ufw allow 8022/tcp` or whatever the syntax for the firewall you're using is).

You shouldn't have to run sudo or mess with any sshd_config files or anything like that. Usually how I'll access it is just with whatever file browser I'm using like `sftp://x.x.x.x:8022/` or with something like winscp or filezilla.

**Comment by e101sg** [comment] 2023-02-23 07:18
Is sshd running (sudo systemctl status sshd)? Think so. Please refer the screen shot below.
`expose SFTP server (for PCAP upload) to external hosts? (y/N), and if you answer 'Hit should set up that port forwarding for you 
`
YES, enabled this option as well. Will check the docker-compose.yml file.
Thanks for useful points. Cheers!
 
![sshd](https://user-images.githubusercontent.com/1925934/220841437-89872bd2-f468-41f6-b555-eb79a28787d4.png)

**Comment by Njinx** [comment] 2023-02-23 19:27
Is this just a regular Ubuntu installation? Can you post the contents of `/etc/ssh/sshd_config`?

**Comment by Njinx** [comment] 2023-02-23 19:29
Are you running a normal Ubuntu installation? Can you post the contents of `/etc/ssh/sshd_config`?

**Comment by mmguero** [comment] 2023-02-23 19:53
You shouldn't have to do anything with your local SSHD_config or do anything with systemctl. Malcolm is not using your hosts SSH server, it is using a server inside a docker container. This is not managed by systemctl and does not conflict or have anything to do with your local SSH configuration

**Comment by mmguero** [comment] 2023-02-23 19:54
At least, when it comes to the internal SSH server used to be able to upload PCAP files for processing. As far as SSH into your own host you can check your distributions documentation for that.

**Comment by Njinx** [comment] 2023-02-23 20:09
> At least, when it comes to the internal SSH server used to be able to upload PCAP files for processing. As far as SSH into your own host you can check your distributions documentation for that.

From what I understand in the original post @e101sg is having trouble SSH'ing into the host machine itself. @e101sg can you clarify?

**Comment by mmguero** [comment] 2023-02-24 16:51
I guess the original text of the issue is describing both, which are two different things:

> As described in the document, the SFTP server is running on 8022. But how to connect and upload the pcap file automatically or how to to ssh to Malcolm it self.

My comments apply to the bit about the SFTP server published by the `upload` container for adding PCAPs via SFTP/SCP. As far as sshing into "Malcolm itself" it'll either depend on your distribution (if you're just running Malcolm in docker), or if you're running Malcolm from the Malcolm ISO installer then yes, you'd need to potentially enable it with systemctl and/or check /etc/ssh/sshd_config

**Comment by e101sg** [comment] 2023-02-26 16:28
> You shouldn't have to do anything with your local SSHD_config or do anything with systemctl. Malcolm is not using your hosts SSH server, it is using a server inside a docker container. This is not managed by systemctl and does not conflict or have anything to do with your local SSH configuration

Okay.Noted. yes, i am running normal 22.04 Ubuntu. For access  SSH/SFTP on Ubuntu host machine  not related to Malcolm. Got the answer for the first issue. 
Now, the second case, sshing into "Malcolm itself"( (running Malcolm in docker) for auto PCAP file upload, 
do i need to change the something on `upload` container ?! May be a noob question.
 Thanks a lot.

**Comment by mmguero** [comment] 2023-02-27 14:30
There are 3 ways to get previously captured tcpdump-formatted PCAP files into Malcolm:

1. Through the upload web interface (at https://<ip address>/upload)
2. By copying the PCAP files directly into Malcolm's PCAP upload directory (by default, `./pcap/upload` under the Malcolm installation directory)
3. By using SFTP/SCP to an internal SSHD instance running in the `upload` container and surfaced through docker on port 8022.

To use method 3 above, note the following:

* whether this is available on localhost only (on the host running Malcolm) or whether the port is available to other hosts depends on the port mapping value in the docker-compose file: 
    * `grep 8022 docker-compose.yml`
        * `- "127.0.0.1:8022:22"` <--- the 127.0.0.1 indicates it will be available to localhost only, vs.
        * `- "0.0.0.0:8022:22"` <--- the 0.0.0.0 indicates it will be available to other hosts as well (barring access through firewall external to Malcolm's control)

* connecting via SSH itself (i.e., to get a shell) will not work, only SFTP/SCP will work:

```
ssh -p 8022 analyst@localhost
analyst@localhost's password: 
This service allows sftp connections only.
Connection to localhost closed.
```

* besides command-line transfer of the files via the `scp` utility, I've tested graphical tools like WinSCP and FileZilla with success:

![Screenshot_2023-02-27_07-27-33](https://user-images.githubusercontent.com/13872653/221590560-ded692a2-5838-446b-a396-07ff3e4dc661.png)

* the username/password used for this connection is set up with `./scripts/auth_setup` and its information is stored in `./auth.env` in the Malcolm directory. LDAP authentication or users other than the one stored in `auth.env` don't work with this method

* only tcpdump-formated PCAP files are currently supported for upload to Malcolm (not PCAPNG format)

* when you connect to the SFTP server, you'll see a directory named `files` and a `README.txt` which reads `Put your files into /files. Don't use subdirectories.`

*  Upon transferring a file to this `files` directory, you'll see some sort of corresponding message in the docker containers' output logs noting something like this:
    * `malcolm-pcap-monitor-1        | renamed '/pcap/upload/foobar.pcap' -> '/pcap/processed/foobar.pcap'`

I hope that clears up all of the confusion. I spent about a half hour this morning testing and double-checking all of the above to confirm it all works as I've described.

**Closed as completed** 2023-02-27 14:31 UTC
Labels: invalid

**Comment by e101sg** [comment] 2023-02-28 02:35
Excellent and detailed reply. Appreciate  your time and efforts!  Thanks a lot.
